# The Docker image that will be used to build your app
image:
   name: ghcr.io/fenics/dolfinx/lab:nightly
   entrypoint: [""]
# Functions that should be executed before the build script is run

variables: 
    HDF5_MPI: "ON"
    HDF5_DIR: "/usr/local/"
    DISPLAY: ":99.0"
    DEB_PYTHON_INSTALL_LAYOUT: deb_system
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip" 
    PYVISTA_OFF_SCREEN: "false"
    PYVISTA_TRAME_SERVER_PROXY_PREFIX: '/proxy/'
    PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
    PYVISTA_OFF_SCREEN: "False"
    PYVISTA_JUPYTER_BACKEND: "panel"
    PUBLISH_DIR: "./_build/html"
    DEB_PYTHON_INSTALL_LAYOUT: "deb_system"

before_script:
  - apt-get update && apt-get install -y libgl1-mesa-glx libxrender1 xvfb
  - python3 -m pip install -U pip
  - python3 -m pip install --no-binary=h5py git+https://github.com/h5py/h5py@master
  - python3 -m pip install -r docker/requirements.txt

pages:
  script:
    - jupyter-book build . -W
    - mv notebooks/_build/html/ public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
