# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FEniCSx Fracture Mechanics
author: Newfrac Network
logo: images/logo.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

  # Set timeout for any example to 20 minutes
  timeout: 1800
# Define the name of the latex output file for PDF builds
#latex:
#  latex_documents:
#    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://newfrac.github.io/fenicsx-fracture/ # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

  # Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    suppress_warnings: ["mystnb.unknown_mime_type"]

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"git a
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: custom   

html_theme_options:
    repository_provider: "github"  # or "github", "bitbucket",
    repository_url: "https://github.com/newfrac/fenicsx-fracture"

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

  extra_footer: |
    <div>
      Funded by the European Commission under a Marie Skłodowska-Curie Actions Grant Agreement n. 861061. 
    </div>

exclude_patterns: [README.md]
