# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NewFrac FEniCSx Training
author: Jack Hale, Corrado Maurini
logo: images/logo.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

  # Set timeout for any example to 20 minutes
  timeout: 1800
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://gitlab.com/newfrac//newfrac-fenicsx-training # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

  # Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

  extra_footer: |
    <div>
        This webpage is internal to the Newfrac network.
    </div>

exclude_patterns: [README.md]
