name: Test stable build of book

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build-book:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/lab:v0.6.0-r1
   
    env:
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: '/proxy/'
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "panel"

    steps:

      - uses: actions/checkout@v3
  
      - name: Install common packages
        uses: ./.github/actions/install-dependencies

      - name: Install book deps
        run:
          python3 -m pip install -r docker/requirements.txt

      - name: Build the book
        run: 
          jupyter-book build . -W

      - uses: actions/upload-artifact@v3
        with:
          name: webpage
          path: ;/_build/html
          retention-days: 2
          if-no-files-found: error
